sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t harrisleesh/docker-react-app -f Dockerfile.dev .

install:
  - docker run -e CI=true harrisleesh/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "sh-docker-test-app"
  env: "Shdockertestapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-749986755890"
  bucket_path: "sh-docker-test-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key: $AWS_SECRET_ACCESS_KEY